version: '2'

services:

  store-product-service:
    image: ozdemirkan/store-product-service
    container_name: store-product-service
    mem_limit: 512M
    entrypoint: ["java", "-jar", "/app.jar"]
    ports:
      - 8081:8081

  store-order-service:
    image: ozdemirkan/store-order-service
    container_name: store-order-service
    mem_limit: 512M
    entrypoint: ["java", "-jar", "/app.jar"]
    ports:
      - 8082:8082
    environment:
      - JAVA_TOOL_OPTIONS=-Dmw.service.product.url=http://store-product-service:8081
  store-gateway-service:
    image: ozdemirkan/store-gateway-service
    container_name: store-gateway-service
    mem_limit: 512M
    entrypoint: ["java", "-jar", "/app.jar"]
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=-Dspring.cloud.gateway.routes[0].uri=http://store-product-service:8081 -Dspring.cloud.gateway.routes[0].predicates[0]=Path=/api/product/** -Dspring.cloud.gateway.routes[1].uri=http://store-order-service:8082 -Dspring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**

